name: TrpB
model:
  _target_: sgpo.problem.basic.XOR
  ratio: 0.5
  length: 389

data:
  _target_: sgpo.data.protein.ProteinPredictorDataset
  data_config:
    name: TrpB
    data_path: sgpo.data/TrpB_fitness.csv
    full_seq: MKGYFGPYGGQYVPEILMGALEELEAAYEGIMKDESFWKEFNDLLRDYAGRPTPLYFARRLSEKYGARVYLKREDLLHTGAHKINNAIGQVLLAKLMGKTRIIAETGAGQHGVATATAAALFGMECVIYMGEEDTIRQKLNVERMKLLGAKVVPVKSGSRTLKDAIDEALRDWITNLQTTYYVFGSVVGPHPYPIIVRNFQKVIGEETKKQIPEKEGRLPDYIVACVSGGSNAAGIFYPFIDSGVKLIGVEAGGEGLETGKHAASLLKGKIGYLHGSKTFVLQDDWGQVQVSHSVSAGLDYSGVGPEHAYWRETGKVLYDAVTDEEALDAFIELSRLEGIIPALESSHALAYLKKINIKGKVVVVNLSGRGDKDLESVLNHPYVRERIR
    seq_len: 389
    residues: [183, 184, 227, 228] #mutated positions, this uses 1 indexing
    # tokenizer: #use the one from evodiff
    n_samples: 10000
    seed: 42
    alphabet_size: 26
exp_dir: exps/protein

