name: protein_DPO
sample_batch_size: 50 #batch size for inference, can probably increase this for the smaller model and it will still fit on memory

train:
  mode: weighted #ranked #weighted #paired currently not supported
  batch_size: 8 #batch size for training, used to work with much larger batch sizes (i.e. 15, but 4 is the max for the big model)
  #mostly from CONFIG in https://github.com/AI4PDLab/DPO_pLM/blob/main/DPO_pLM.py#L105
  n_epochs: 5 #tried 5 before
  beta: 2. #0.25 is better for CreiLOV #0.01 #seems to weight the strength of the value function, 0.01 in stocco et al. but bigger values seem to work better for our applicaiton
  seed: 42
  learning_rate: 1e-6 #1e-6 for other cases too #1e-7 from stocco et al. #used to run this higher at like 1e-4?
  split_percent: 0.2
  adam_betas: [0.9, 0.98]
  epsilon: 1e-8
  adam_decay: 0.1
  device: cuda
  wandb: True #False

data:
  _target_: sgpo.dataset.protein.ProteinPredictorDataset

train_function:
  _target_: sgpo.training.train_DPO.train_DPO

exp_dir: exps/protein