name: protein
model:
  _target_: sgpo.problem.basic.XOR
  ratio: 0.5
  length: 400

# data:
#   _target_: sgpo.data.mnist.MNIST
#   train: False
#   discrete: True

exp_dir: exps/protein

