name: NOS
time_conditioned: True
guidance_params: [1., 10., 100, 200., 500.] #stability coeffs to iterate through for actual pareto runs

#only used for hyperparameter search
nos_steps: [5, 10]
nos_step_sizes: [0.5, 2., 5.]
nos_stability_coefs: [0.1, 1., 10., 100., 1000.]

method:
  _target_: sampling.NOS.NOS_C
  num_nos_steps: 10 #5, 10
  nos_step_size: 2. #0.1 #0.5-2 #try smaller here if it's unstable? #1 was unstable here #bug here because lowering it didn't change the results
  nos_stability_coef: 200.
  n_max_mutations: