name: TrpB_masked
data_path: sgpo.data/TrpB_fitness.csv
full_seq: MKGYFGPYGGQYVPEILMGALEELEAAYEGIMKDESFWKEFNDLLRDYAGRPTPLYFARRLSEKYGARVYLKREDLLHTGAHKINNAIGQVLLAKLMGKTRIIAETGAGQHGVATATAAALFGMECVIYMGEEDTIRQKLNVERMKLLGAKVVPVKSGSRTLKDAIDEALRDWITNLQTTYYVFGSVVGPHPYPIIVRNFQKVIGEETKKQIPEKEGRLPDYIVACVSGGSNAAGIFYPFIDSGVKLIGVEAGGEGLETGKHAASLLKGKIGYLHGSKTFVLQDDWGQVQVSHSVSAGLDYSGVGPEHAYWRETGKVLYDAVTDEEALDAFIELSRLEGIIPALESSHALAYLKKINIKGKVVVVNLSGRGDKDLESVLNHPYVRERIR
seq_len: 389
residues: [183, 184, 227, 228] #mutated positions, this uses 1 indexing, if None, then use all residues
seed: 42
alphabet_size: 26 #don't hardcode this in the future
pretraining:
  dataset_path: sgpo.data/TrpB_MSA_masked.csv
  splits: [train, validation]